CREATE TABLE `Language` (
`Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
`Language` TEXT NOT NULL
);

CREATE TABLE `Cohort` (
`Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
`Cohort` TEXT NOT NULL,
`LanguageId` INTEGER,
FOREIGN KEY(`LanguageId`) REFERENCES `Language`(`Id`)
);

CREATE TABLE `Instructors` (
`Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
`Name` TEXT NOT NULL
);

CREATE TABLE `InstructorType` (
`Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
`Type` TEXT NOT NULL
);


CREATE TABLE `CohortInstructors` (
`Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
`CohortId` INTEGER,
`InstructorsId` INTEGER,
`Type` INTEGER,
FOREIGN KEY(`InstructorsId`) REFERENCES `Instructors`(`Id`),
FOREIGN KEY(`CohortId`) REFERENCES `Cohort`(`Id`),
FOREIGN KEY(`Type`) REFERENCES `InstructorType`(`Id`)
);

CREATE TABLE `Student` (
`Id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
`Name` TEXT NOT NULL,
`CohortId` INTEGER,
FOREIGN KEY(`CohortId`) REFERENCES `Cohort`(`Id`)
);


